# This is the production variant of
# docker deployment for twitter_handler app
version: '3'
services:
  
  # development instance
  twitter_handler-development:
    image: index.docker.io/sandydock/backend:development
    container_name: 'twitter_handler-development'
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - MONGO_HOST=database
      - MONGO_DB=twitter_handler-development
    env_file:
      - .env
  

  
  # production instance
  twitter_handler:
    image: index.docker.io/sandydock/backend:master
    container_name: 'twitter_handler'
    ports:
      - 3001:3000
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - MONGO_HOST=database
      - MONGO_DB=twitter_handler
    env_file:
      - .env
  

  # database configuration for the project
  database:
    image: mongo:3.4.0
    container_name: 'mongodb'
    volumes:
      - ./data/db:/data/db
    restart: always
    ports:
      - "27017:27017"
  
  # nginx for port forwarding and proxy server
  nginx: 
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - tutable
      - tutable-development
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs
  
  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup